/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(time_mode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(32d630ce5dd1485da350ac677846917e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <sigmf/time_mode.h>

void bind_time_mode(py::module& m)
{
    py::enum_<::gr::sigmf::sigmf_time_mode>(m,"sigmf_time_mode")
        .value("absolute", ::gr::sigmf::sigmf_time_mode::absolute) // 0
        .value("relative", ::gr::sigmf::sigmf_time_mode::relative) // 1
        .export_values()
    ;

    py::implicitly_convertible<int, ::gr::sigmf::sigmf_time_mode>();
}
