/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(usrp_gps_message_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(16dc261f3d9f27739e728ef2a0ad91b0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <sigmf/usrp_gps_message_source.h>
// pydoc.h is automatically generated in the build directory
#include <usrp_gps_message_source_pydoc.h>

void bind_usrp_gps_message_source(py::module& m)
{

    using usrp_gps_message_source    = ::gr::sigmf::usrp_gps_message_source;

    py::class_<usrp_gps_message_source, gr::block, gr::basic_block,
        std::shared_ptr<usrp_gps_message_source>>(m, "usrp_gps_message_source", D(usrp_gps_message_source))

        // Use a lambda here so that we can explicitly convert UHD args to a device_addr_t,
        // and thus resolve the overloaded make() method.
        .def(py::init([](const std::string uhd_args, double poll_interval) {
              ::uhd::device_addr_t addr(uhd_args);
              return usrp_gps_message_source::make(addr, poll_interval);
        }))
        ;
}
